version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    reviewers:
      - 'citizensadvice/devops'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/London'
